### ISSUE TITLE
/transactions/internal/address/`addr`: x total count is 0 

### ISSUE THREAD

**Issue by Rheannone** [geometry-labs/icon-tracker-frontend#205]
content-length: "1053"
content-type: "text/plain; charset=utf-8"
x-total-count: "0"

Request URL: https://tracker.icon.community/api/v1/transactions/internal/address/hx68646780e14ee9097085f7280ab137c3633b4b5f?address=hx68646780e14ee9097085f7280ab137c3633b4b5f&limit=10&skip=0
Request Method: GET
Status Code: 200

**Comment by pranav925** [comment]
This address has no internal transactions: 

https://tracker.icon.foundation/address/hx68646780e14ee9097085f7280ab137c3633b4b5f
