### ISSUE TITLE
Address Tx: returning empty [] instead of 404

### ISSUE THREAD

**Issue by Rheannone** [geometry-labs/icon-tracker-frontend#245]
https://tracker.berlin.geometry.io/api/v1/transactions/address/hxcd6f04b2a5184715ca89e523b6c823ceef2f9c3d

**Comment by pranav925** [comment]
Live tracker says no transactions: 

https://berlin.tracker.solidwallet.io/address/hxcd6f04b2a5184715ca89e523b6c823ceef2f9c3d

**Comment by Rheannone** [comment]
it makes sense it's empty. It was causing an error on testnet because on mainnet instead of [], this returns 404. Worked around. I'll move this to done.
