### ISSUE TITLE
Governance/Votes/Address: Returning 200 but error 

### ISSUE THREAD

**Issue by Rheannone** [geometry-labs/icon-tracker-frontend#247]
https://tracker.berlin.geometry.io/api/v1/governance/votes/hxbc2f530a7cb6170daae5876fd24d5d81170b93fe

**Comment by shinyfoil** [comment]
Oh, this is related to mappings. I'll make the fix in a sec.

**Comment by shinyfoil** [comment]
Fixed in https://github.com/geometry-labs/icon-charts/commit/0b58a21e31b9968b81fa748a1f9524196e55748a
